{
 "title": "AWS ALB",
 "description": "AWS ALB JSON access logs.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "source_env",
    "label": "source_env",
    "query": {}
   },
   { "name": "domain_filter_regex", "label": "domain_filter_regex" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"left dashboard-header\">\n   <img src=\"https://marketplace-assets.digitalocean.com/logos/loki-logo.svg\" style=\"height:29px;\"/>\n  <span>AWS ALB Dashboard</span>\n</div>"
   }
  },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({source=\"aws.alb_accesslog\", source_env=~\"$source_env\"} |= \"request_verb\" | json request_url=\"request_url\" | request_url =~ `$domain_filter_regex` [$__interval]))"
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (target_status_code) (count_over_time({source=\"aws.alb_accesslog\", source_env=~\"$source_env\"} |= \"request_proto\" | json | request_url =~ `$domain_filter_regex` |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status: {{target_status_code}}"
    }
   ]
  },
  {
   "title": "% of  4/5xx ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " sum(rate({source=\"aws.alb_accesslog\", source_env=~\"$source_env\"} |= \"request_proto\" | json | request_url =~ `$domain_filter_regex` | target_status_code >= 400 | __error__=\"\" [$__interval])) / (sum(rate({source=\"aws.alb_accesslog\", source_env=~\"$source_env\"} |= \"request_proto\" | json | request_url =~ `$domain_filter_regex` | __error__=\"\" [$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time({source=\"aws.alb_accesslog\", source_env=~\"$source_env\"} |= \"request_proto\" | json | request_url =~ `$domain_filter_regex` | target_status_code = 200 | unwrap received_bytes |  __error__=\"\" [$__interval])",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Users right now",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (client_ip) (count_over_time({source=\"aws.alb_accesslog\", source_env=~\"$source_env\"} |= \"request_proto\" | json | request_url =~ `$domain_filter_regex` |  __error__=\"\" [$__interval])))"
    }
   ]
  },
  {
   "title": " 4/5xx  Services",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " sum by (target_status_code,domain_name) (count_over_time({source=\"aws.alb_accesslog\", source_env=~\"$source_env\"} |= \"request_proto\" | json | request_url =~ `$domain_filter_regex` | target_status_code >= 400 |__error__=\"\" [$__interval]))",
     "legendFormat": " {{domain_name}} / {{target_status_code}} "
    }
   ]
  },
  {
   "title": "Requests Route",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum by (domain_name) (\n        count_over_time(\n            {source=\"aws.alb_accesslog\", source_env=~\"$source_env\"} |= \"request_proto\" | json | request_url =~ `$domain_filter_regex` |  __error__=\"\" [$__interval]\n        )\n    )\n    ,\"domain_name\", \"fixed-response\", \"domain_name\", \"\"\n)",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": "Logs By Env - \"$source_env\" - \"$domain_filter_regex\" (Filtered)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "{source=\"aws.alb_accesslog\", source_env=~\"$source_env\"} |= \"request_proto\" | json | request_url =~ `$domain_filter_regex` | line_format \"STATUS:{{.elb_status_code}} - CLIENT:{{.client_ip}} - REQUEST:{{.request_verb}} {{.request_url}} - ACTION:[{{.actions_executed}}] - ROUTE_TO:{{.target_ip}}\""
    }
   ]
  },
  {
   "title": "95th percentile of Target Processing Time",
   "type": "timeseries",
   "description": "95th percentile of the time elapsed, in seconds, after the request leaves the load balancer until the target starts to send the response headers.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95, {source=\"aws.alb_accesslog\", source_env=~\"$source_env\"} |= \"target_processing_time\" | json | request_url =~ `$domain_filter_regex` | unwrap target_processing_time |  __error__=\"\"  [$__interval]) by (domain_name)",
     "legendFormat": " {{domain_name}}"
    }
   ]
  },
  {
   "title": "Max Target Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (domain_name) (max_over_time({source=\"aws.alb_accesslog\", source_env=~\"$source_env\"} |= \"target_processing_time\" | json | request_url =~ `$domain_filter_regex` | unwrap target_processing_time |  __error__=\"\"  [$__interval]))",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": "Requests Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (domain_name) (sum_over_time({source=\"aws.alb_accesslog\", source_env=~\"$source_env\"} |= \"domain_name\" | json | request_url =~ `$domain_filter_regex` | unwrap received_bytes |  __error__=\"\"  [$__interval]))",
     "legendFormat": "{{domain_name}}"
    }
   ]
  }
 ]
}