{
 "title": "Docker Swarm Nodes",
 "description": "Docker Swarm nodes metrics",
 "tags": [
  "prometheus",
  "node-exporter",
  "swarm",
  "linux"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "node_cluster", "label": "Cluster", "query": "label_values(up, node_cluster)" },
   {
    "name": "node_name",
    "label": "Swarm Node",
    "query": "label_values(up{node_cluster=~\"$node_cluster\"}, node_name)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(1, sum(node_time_seconds{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"} - node_boot_time_seconds{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"}) by (node_name))"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_meta{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"})"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\", node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"})"
    }
   ]
  },
  {
   "title": "Total Disk Space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{mountpoint=\"/\", node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"})"
    }
   ]
  },
  {
   "title": "System Load by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load5{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"}",
     "legendFormat": "load5 {{node_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\", node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"}[$interval]) * 100) by (node_name))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Running Services",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "container_start_time_seconds{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\", container_label_com_docker_swarm_service_name!=\"\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\", node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"}[$interval])) * 100 / count(node_cpu_seconds_total{mode=\"user\", node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"})"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum((node_filesystem_free_bytes{mountpoint=\"/\", node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"} / node_filesystem_size_bytes{mountpoint=\"/\", node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"}) * 100) / count(node_meta{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"})"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum((node_memory_MemAvailable_bytes{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"} / node_memory_MemTotal_bytes{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"}) * 100) / count(node_meta{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"})"
    }
   ]
  },
  {
   "title": "Memory usage by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"} - node_memory_MemFree_bytes{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"} - node_memory_Cached_bytes{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"} - node_memory_Buffers_bytes{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"} - node_memory_Slab_bytes{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"}) by (node_name)",
     "legendFormat": "Used {{node_name}}"
    },
    {
     "expr": "sum(node_memory_Cached_bytes{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"}) by (node_name)",
     "legendFormat": "Cached {{node_name}}"
    }
   ]
  },
  {
   "title": "Filesystem space available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"}",
     "legendFormat": "{{node_name}} - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk I/O by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"}[$interval])) by (node_name)",
     "legendFormat": "Read {{node_name}}"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"}[$interval])) by (node_name)",
     "legendFormat": "Written {{node_name}}"
    }
   ]
  },
  {
   "title": "IOPS by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_reads_completed_total{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"}[$interval])) by (node_name)",
     "legendFormat": "Reads {{node_name}}"
    },
    {
     "expr": "sum(irate(node_disk_writes_completed_total{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"}[$interval])) by (node_name)",
     "legendFormat": "Writes {{node_name}}"
    }
   ]
  },
  {
   "title": "CPU IO Wait by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg(irate(node_cpu_seconds_total{mode=\"iowait\", node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"}[$interval]) * 100) by (node_name))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Running Containers by Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node_name, container_label_com_docker_swarm_service_name) (rate(container_last_seen{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\", container_label_com_docker_swarm_service_name!=\"\"}[5m]))",
     "legendFormat": "{{ container_label_com_docker_swarm_service_name }}"
    }
   ]
  },
  {
   "title": "Total Containers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\", container_label_com_docker_swarm_service_name!=\"\"})"
    }
   ]
  },
  {
   "title": "Containers Network Traffic by Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (node_name) (rate(container_network_receive_bytes_total{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\", container_label_com_docker_swarm_service_name!=\"\"}[$interval]))",
     "legendFormat": "IN {{node_name}}"
    },
    {
     "expr": "- sum by (node_name) (rate(container_network_transmit_bytes_total{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\", container_label_com_docker_swarm_service_name!=\"\"}[$interval]))",
     "legendFormat": "OUT {{node_name}}"
    }
   ]
  },
  {
   "title": "Cluster members",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_meta{node_cluster=~\"$node_cluster\", node_name=~\"$node_name\"}) by (node_id, node_name, node_cluster, instance)"
    }
   ]
  }
 ]
}