{
 "title": "Traefik",
 "description": "Traefik JSON access logs.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": {}
   },
   { "name": "domain_filter_regex", "label": "domain_filter_regex" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"left dashboard-header\">\n   <img src=\"https://marketplace-assets.digitalocean.com/logos/loki-logo.svg\" style=\"height:29px;\"/>\n  <span>Traefik Dashboard</span>\n</div>"
   }
  },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service_name=\"traefik\", source_env=~\"$env\"} |= \"RequestProtocol\" | json RequestAddr=\"RequestAddr\" | RequestAddr =~ `$domain_filter_regex` [$__interval]))"
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (OriginStatus) (count_over_time({service_name=\"traefik\", source_env=~\"$env\"}|= \"RequestProtocol\" | json | RequestAddr =~ `$domain_filter_regex` |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status: {{OriginStatus}}"
    }
   ]
  },
  {
   "title": "% of  4/5xx ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " sum(rate({service_name=\"traefik\", source_env=~\"$env\"} |~ \"RequestProtocol\" | json | RequestAddr =~ `$domain_filter_regex` | OriginStatus >= 400 |__error__=\"\"[$__interval])) / (sum(rate({service_name=\"traefik\", source_env=~\"$env\"} |~ \"RequestProtocol\" | json | RequestAddr =~ `$domain_filter_regex` | __error__=\"\"[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time({service_name=\"traefik\", source_env=~\"$env\"}|= \"RequestProtocol\" | json | RequestAddr =~ `$domain_filter_regex` | OriginStatus=200 | unwrap DownstreamContentSize |  __error__=\"\" [$__interval])",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Users right now",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (ClientHost) (count_over_time({service_name=\"traefik\", source_env=~\"$env\"}|= \"RequestProtocol\" | json | RequestAddr =~ `$domain_filter_regex` |  __error__=\"\" [$__interval])))"
    }
   ]
  },
  {
   "title": " 4/5xx  Services",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " sum by (OriginStatus,ServiceName) (count_over_time({service_name=\"traefik\", source_env=~\"$env\"} |~ \"RequestProtocol\" | json | RequestAddr =~ `$domain_filter_regex` | OriginStatus >= 400 |__error__=\"\"[$__interval]))",
     "legendFormat": " {{ServiceName}} / {{OriginStatus}} "
    }
   ]
  },
  {
   "title": "Requests Route",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n    sum by (RouterName) (\n        count_over_time(\n            {service_name=\"traefik\", source_env=~\"$env\"} |= \"RequestProtocol\"\n            | json\n            | RequestAddr =~ `$domain_filter_regex`\n            |  __error__=\"\"\n            [$__interval]\n        )\n    )\n    ,\"RouterName\", \"proxy-internal\", \"RouterName\", \"\"\n)",
     "legendFormat": "{{RouterName}}"
    }
   ]
  },
  {
   "title": "Logs By Env - \"$env\" - \"$domain_filter_regex\" (Filtered)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "{service_name=\"traefik\", source_env=~\"$env\"} |= \"RequestProtocol\" | json | RequestAddr =~ `$domain_filter_regex` | line_format \"Status:{{.OriginStatus}} Client From {{.ClientAddr}} {{.RequestMethod}} {{.RequestAddr}}{{.RequestPath}} Route To {{.ServiceAddr}}\""
    }
   ]
  },
  {
   "title": "95th percentile of Request Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{service_name=\"traefik\", source_env=~\"$env\"} |= \"RequestProtocol\"| json | RequestAddr =~ `$domain_filter_regex` | unwrap Duration |  __error__=\"\"  [$__interval]) by (ServiceName)",
     "legendFormat": " {{ ServiceName }}"
    }
   ]
  },
  {
   "title": "Max Age of Request Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "max by (ServiceName) (max_over_time({service_name=\"traefik\", source_env=~\"$env\"} |= \"RequestProtocol\" | json | RequestAddr =~ `$domain_filter_regex` | unwrap Duration |  __error__=\"\"  [$__interval]))",
     "legendFormat": "{{ ServiceName}}"
    }
   ]
  },
  {
   "title": "Requests Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (ServiceName) (sum_over_time({service_name=\"traefik\", source_env=~\"$env\"} |= \"RequestProtocol\" | json | RequestAddr =~ `$domain_filter_regex` | unwrap RequestContentSize |  __error__=\"\"  [$__interval]))",
     "legendFormat": "{{ ServiceName}}"
    }
   ]
  }
 ]
}