# service configuration
service:
  # Flush
  # =====
  # set an interval of seconds before to flush records to a destination
  flush: 1

  # Daemon
  # ======
  # instruct Fluent Bit to run in foreground or background mode.
  daemon: Off

  # Log_Level
  # =========
  # Set the verbosity level of the service, values can be:
  #
  # - error
  # - warning
  # - info
  # - debug
  # - trace
  #
  # by default 'info' is set, that means it includes 'error' and 'warning'.
  log_level: ${FLUENT_BIT_LOG_LEVEL}

  # Parsers File
  # ============
  # specify an optional 'Parsers' configuration file
  parsers_file: parsers.conf

  # Plugins File
  # ============
  # specify an optional 'Plugins' configuration file to load external plugins.
  plugins_file: plugins.conf

  # HTTP Server
  # ===========
  # Enable/Disable the built-in HTTP Server for metrics
  http_server: On
  http_listen: 0.0.0.0
  http_port: 2020

  # Storage
  # =======
  # Fluent Bit can use memory and filesystem buffering based mechanisms
  #
  # - https://docs.fluentbit.io/manual/administration/buffering-and-storage
  # - https://docs.fluentbit.io/manual/administration/buffering-and-storage#service-section-configuration
  #
  storage.metrics: on
  storage.path: ${FLUENT_STORAGE_PATH}
  storage.sync: normal
  storage.checksum: off
  storage.backlog.mem_limit: 5M

  # Scheduling
  # ==========
  # Determine the waiting time before a retry will happen
  #
  # - https://docs.fluentbit.io/manual/administration/scheduling-and-retries
  #
  scheduler.cap: 2000
  scheduler.base: 5

pipeline:
  filters:
    # Ensure any JSON logs are evaluated and flattened
    - name: lua
      match: ${FLUENT_BIT_TAG_PREFIX}*
      script: flatten-json.lua
      call: flatten_json

    # Ensure all logs are formatted correctly for graylog
    - name: lua
      match: ${FLUENT_BIT_TAG_PREFIX}*
      script: apply-standard-record-formatting.lua
      call: standard_record_formatting

includes:
  # Debugging STDOUT Output (enabled by default)
  - fluent-bit.debug.output.yaml
  # HTTP Input
  #- fluent-bit.http.input.yaml
  # TLS Forward Input
  #- fluent-bit.tls-forward.input.yaml
  # PT Forward Input
  #- fluent-bit.pt-forward.input.yaml
  # Loki Output
  #- fluent-bit.grafana-loki.output.yaml
  # TLS Forward Output
  #- fluent-bit.tls-forward.output.yaml
  # PT Forward Output
  #- fluent-bit.pt-forward.output.yaml
