###
# File: fluent-bit.pt-forward.input.yaml
# Project: fluent-bit
# File Created: Monday, 23rd June 2025 1:12:43 am
# Author: Josh.5 (jsunnex@gmail.com)
# -----
# Last Modified: Monday, 23rd June 2025 1:12:59 am
# Modified By: Josh.5 (jsunnex@gmail.com)
###

# -- Custom config for pt forward input added here --
